# Generated by Django 2.2.9 on 2020-02-23 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('kudo_date', models.DateField(auto_now_add=True)),
                ('kudo_count', models.IntegerField()),
                ('from_user_id', models.ForeignKey(on_delete=True, related_name='from_user_id', to=settings.AUTH_USER_MODEL)),
                ('to_user_id', models.ForeignKey(on_delete=True, related_name='to_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
