# Generated by Django 2.2.9 on 2020-02-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givekudo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kudo',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='kudo',
            old_name='to_user_id',
            new_name='to_user',
        ),
    ]
